# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pkg_resources

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(705, 378)
        Dialog.setMinimumSize(QtCore.QSize(705, 378))
        Dialog.setMaximumSize(QtCore.QSize(705, 378))
        Dialog.setStyleSheet("background-color: rgb(216, 255, 247);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 721, 71))
        self.frame.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(150, 20, 80, 51))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 0, 111, 71))
        self.frame_2.setStyleSheet("image: url(images/edit.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(380, 40, 301, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_effacer = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_effacer.setFont(font)
        self.pushButton_effacer.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"selection-background-color: rgb(170, 255, 255);\n"
"selection-color: rgb(170, 0, 0);\n"
"color: rgb(255, 0, 0);")
        self.pushButton_effacer.setObjectName("pushButton_effacer")
        self.horizontalLayout_9.addWidget(self.pushButton_effacer)
        self.pushButton_enregistrer = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_enregistrer.setFont(font)
        self.pushButton_enregistrer.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"selection-color: rgb(170, 255, 255);\n"
"selection-color: rgb(0, 170, 0);\n"
"color: rgb(0, 255, 0);")
        self.pushButton_enregistrer.setObjectName("pushButton_enregistrer")
        self.horizontalLayout_9.addWidget(self.pushButton_enregistrer)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 310, 731, 41))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(560, 350, 104, 13))
        self.label_10.setObjectName("label_10")
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(40, 130, 298, 128))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setMinimumSize(QtCore.QSize(88, 23))
        self.label_2.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_prenom = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_prenom.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_prenom.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_prenom.setFont(font)
        self.lineEdit_prenom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_prenom.setObjectName("lineEdit_prenom")
        self.horizontalLayout.addWidget(self.lineEdit_prenom)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setMinimumSize(QtCore.QSize(88, 23))
        self.label_3.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_nom = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_nom.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_nom.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nom.setFont(font)
        self.lineEdit_nom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.horizontalLayout_2.addWidget(self.lineEdit_nom)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setMinimumSize(QtCore.QSize(88, 23))
        self.label_4.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_age = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_age.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_age.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_age.setFont(font)
        self.lineEdit_age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.horizontalLayout_3.addWidget(self.lineEdit_age)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setMinimumSize(QtCore.QSize(88, 23))
        self.label_5.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_tel = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_tel.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_tel.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_tel.setFont(font)
        self.lineEdit_tel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.horizontalLayout_4.addWidget(self.lineEdit_tel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(370, 131, 298, 128))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setMinimumSize(QtCore.QSize(88, 23))
        self.label_6.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_date = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_date.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_date.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_date.setFont(font)
        self.lineEdit_date.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.horizontalLayout_5.addWidget(self.lineEdit_date)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setMinimumSize(QtCore.QSize(88, 23))
        self.label_7.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_somme_A = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_somme_A.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_somme_A.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_somme_A.setFont(font)
        self.lineEdit_somme_A.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_somme_A.setObjectName("lineEdit_somme_A")
        self.horizontalLayout_6.addWidget(self.lineEdit_somme_A)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setMinimumSize(QtCore.QSize(88, 23))
        self.label_8.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit_somme_B = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_somme_B.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_somme_B.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_somme_B.setFont(font)
        self.lineEdit_somme_B.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_somme_B.setObjectName("lineEdit_somme_B")
        self.horizontalLayout_7.addWidget(self.lineEdit_somme_B)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setMinimumSize(QtCore.QSize(88, 23))
        self.label_9.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_somme_T = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_somme_T.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_somme_T.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_somme_T.setFont(font)
        self.lineEdit_somme_T.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 255);")
        self.lineEdit_somme_T.setObjectName("lineEdit_somme_T")
        self.horizontalLayout_8.addWidget(self.lineEdit_somme_T)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Editer"))
        self.pushButton_effacer.setText(_translate("Dialog", "EFFACER"))
        self.pushButton_enregistrer.setText(_translate("Dialog", "ENREGISTRER"))
        self.label_10.setText(_translate("Dialog", "by CCTech224 | 2019"))
        self.label_2.setText(_translate("Dialog", "Prénom"))
        self.label_3.setText(_translate("Dialog", "Nom"))
        self.label_4.setText(_translate("Dialog", "Âge"))
        self.label_5.setText(_translate("Dialog", "Téléphone"))
        self.label_6.setText(_translate("Dialog", "Date_arr"))
        self.label_7.setText(_translate("Dialog", "Somme_A"))
        self.label_8.setText(_translate("Dialog", "Somme_B"))
        self.label_9.setText(_translate("Dialog", "Somme_T"))
